// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveCompressionOptions() {
  return window['go']['main']['App']['ArchiveCompressionOptions']();
}

export function BackupRepositories(arg1, arg2, arg3) {
  return window['go']['main']['App']['BackupRepositories'](arg1, arg2, arg3);
}

export function DefaultArchiveCompressionOption() {
  return window['go']['main']['App']['DefaultArchiveCompressionOption']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
