// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveCompressionOptions():Promise<Array<string>>;

export function BackupRepositories(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectDirectory():Promise<string>;
