name: Build Template
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      extension: ${{ inputs.os == 'windows' && '.exe' || '' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.22'
      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.8.2
      - name: Build ${{ inputs.os }} amd64 application
        run: wails build -platform ${{ inputs.os }}/amd64 -o ${{ inputs.os }}/gethub${{ env.extension }}
      - name: Upload ${{ inputs.os }} amd64 artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: gethub-${{ inputs.os }}_amd64
          path: ./build/bin/${{ inputs.os }}/gethub${{ env.extension }}
