name: CD
on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        platforms: [linux, windows]
        
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.22'
      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.8.2
      - name: Build ${{ matrix.platforms }} application
        run: wails build -platform ${{ matrix.platforms }}/amd64
      - name: Upload ${{ matrix.platforms }} artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: gethub-${{ matrix.platforms }}
          path: ./build/bin/gethub*
