name: Release
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        platforms: [linux, windows]

    runs-on: ubuntu-latest

    steps:
      - name: 'Download ${{ matrix.platforms }} amd64 archive'
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ env.GITHUB_REPOSITORY }}
          version: 'tags/${{ github.event.release.tag_name }}'
          file: 'gethub-${{ matrix.platforms }}_amd64.zip'
      - name: 'Upload ${{ matrix.platforms }} amd64 archive to release'
        run: |
          cd ${{ github.workspace }}
          gh release upload ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
