name: Release Pipeline
on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  release:
    runs-on: ubuntu-latest

    outputs:
      release_url: ${{ steps.release_upload_url.outputs.release_upload_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
          body_path: CHANGELOG.md
      - name: Output release_upload_url
        id: release_upload_url
        run: |
          echo "release_upload_url=${{ steps.create_release.outputs.upload_url }}" >> "$GITHUB_OUTPUT"

  publish:
    strategy:
      matrix:
        platform: [linux, windows]

    runs-on: ubuntu-latest
    needs: release
    env:
      extension: ${{ matrix.platform == 'windows' && '.exe' || '' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev
      - name: Setup Go Environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.22'
      - name: Install Wails CLI
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@v2.8.2
      - name: Build ${{ matrix.platform }} amd64 Application
        run: |
          wails build -platform ${{ matrix.platform }}/amd64 -o gethub${{ env.extension }}
      - name: Archive and Compress ${{ matrix.platform }} amd64 Application
        run: |
          cd build/bin/
          zip ../../gethub-${{ matrix.platform }}_amd64 gethub${{ env.extension }}
      - name: Upload gethub-${{ matrix.platform }}_amd64.zip as Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.release.outputs.release_url }}
          asset_path: ./gethub-${{ matrix.platform }}_amd64.zip
          asset_name: gethub-${{ matrix.platform }}_amd64.zip
          asset_content_type: application/zip
