name: Release Pipeline
on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  release:
    strategy:
      matrix:
        platforms: [linux, windows]

    runs-on: ubuntu-latest
    env:
      extension: ${{ matrix.platforms == 'windows' && '.exe' || '' }}

    steps:
      - name: Build ${{ matrix.platforms }} amd64 Binary
        uses: ./.github/workflows/build-template.yml
        with:
          os: ${{ matrix.platforms }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
          body_path: CHANGELOG.md
      - name: Archive ${{ matrix.platforms }} amd64 Binary
        run: |
          zip ./build/bin/${{ matrix.platforms }}/gethub${{ env.extension }}
      - name: Upload ${{ matrix.platforms }} amd64 Artifact as Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gethub-${{ matrix.platforms }}_amd64.zip
          asset_name: gethub-${{ matrix.platforms }}_amd64.zip
          asset_content_type: application/zip
